from typing import NamedTuple, Callable, List, Dict
from BaseClasses import CollectionState


class RE4RegionData(NamedTuple):
    connecting_regions: List[str] = []


region_data_table: Dict[str, RE4RegionData] = {
    "Menu": RE4RegionData(["R100-Woods", "R400-Mercenaries Village", "R402-Mercenaries Castle", "R403-Mercenaries Complex", "R404-Mercenaries Water", "R500-Separate Ways-Village"]),
    "R100-Woods": RE4RegionData(["R101-Village"]),
    "R101-Village": RE4RegionData(["R102-Underpass", "R103-Farm"]),
    "R103-Farm": RE4RegionData(["R106-The Old House"]),
    "R106-The Old House": RE4RegionData(["R104-Quarry"]),
    "R104-Quarry": RE4RegionData(["R107-Water Processing"]),
    "R107-Water Processing": RE4RegionData(["R105-Chief's House"]),
    "R105-Chief's House": RE4RegionData(["R101-Village"]),
    "R102-Underpass": RE4RegionData(["R108-Church-Graveyard"]),
    "R108-Church-Graveyard": RE4RegionData(["R109-Colosseum"]),
    "R109-Colosseum": RE4RegionData(["R10a-Swamp", "R10e-Canal-Merchant"]),
    "R10e-Canal-Merchant": RE4RegionData([]),
    "R10a-Swamp": RE4RegionData(["R10b-Lake"]),
    "R10b-Lake": RE4RegionData(["R11b-Lake (Night)"]),
    "R11b-Lake (Night)": RE4RegionData(["R11a-Swamp (Night)", "R10c-Waterfall (Night)", "R10d-Merchant Area (Night)"]),
    "R11a-Swamp (Night)": RE4RegionData(["R119-Colosseum (Night)"]),
    "R10d-Merchant Area (Night)": RE4RegionData([]),
    "R10c-Waterfall (Night)": RE4RegionData(["R10e-Canal (Night)"]),
    "R10e-Canal (Night)": RE4RegionData(["R10e-Canal-Merchant (Night)"]),
    "R10e-Canal-Merchant (Night)": RE4RegionData(["R119-Colosseum (Night)"]),
    "R119-Colosseum (Night)": RE4RegionData(["R118-Church-Graveyard (Night)"]),
    "R118-Church-Graveyard (Night)": RE4RegionData(["R117-Inside Church (Night)", "R112-Underpass (Night)"]),
    "R117-Inside Church (Night)": RE4RegionData([]),
    "R112-Underpass (Night)": RE4RegionData(["R111-Village (Night)"]),
    "R111-Village (Night)": RE4RegionData(["R113-Farm (Night)"]),
    "R11c-Cabin (Night)": RE4RegionData(["R11d-Split Road-Checkpoint (Night)", "R11e-Split Road-Long Road (Night)"]),
    "R11d-Split Road-Checkpoint (Night)": RE4RegionData(["R10f-Gondola"]),
    "R11e-Split Road-Long Road (Night)": RE4RegionData(["R10f-Gondola"]),
    "R10f-Gondola": RE4RegionData(["R11f-Barn", "R200-Way To The Castle"]),
    "R11f-Barn": RE4RegionData([]),
    "R200-Way To The Castle": RE4RegionData(["R202-Catapult Road"]),
    "R202-Catapult Road": RE4RegionData(["R207-Barracks"]),
    "R207-Barracks": RE4RegionData(["R203-Castle Gate"]),
    "R203-Castle Gate": RE4RegionData(["R201-Hall"]),
    "R201-Hall": RE4RegionData(["R208-Water Hall", "R219-Trolly Two"]),
    "R208-Water Hall": RE4RegionData(["R205-Prison Area", "R209-Reception Room"]),
    "R205-Prison Area": RE4RegionData([]),
    "R209-Reception Room": RE4RegionData(["R20a-Hallway"]),
    "R20a-Hallway": RE4RegionData(["R20b-Hedge Maze"]),
    "R20b-Hedge Maze": RE4RegionData(["R20c-Gallery"]),
    "R20c-Gallery": RE4RegionData(["R20f-Gallery Two"]),
    "R20f-Gallery Two": RE4RegionData(["R206-Main Hall", "R20a-Hallway"]),
    "R206-Main Hall": RE4RegionData(["R20d-Butler's Quarters", "R210-Trolley Room"]),
    "R20d-Butler's Quarters": RE4RegionData(["R20e-Spare Room"]),
    "R20e-Spare Room": RE4RegionData([]),
    "R210-Trolley Room": RE4RegionData(["R222-Dragon Room", "R201-Hall"]),
    "R222-Dragon Room": RE4RegionData([]),
    "R219-Trolley Two": RE4RegionData(["R211-Main Hall"]),
    "R211-Main Hall": RE4RegionData(["R212-Armoury", "R216-Armor Room", "R213-Novistador Nest"]),
    "R212-Armoury": RE4RegionData([]),
    "R216-Armor Room": RE4RegionData([]),
    "R213-Novistador Hive": RE4RegionData(["R214-Clock Tower (Outside)"]),
    "R214-Clock Tower (Outside)": RE4RegionData(["R217 Clock Tower (Inside)"]),
    "R217-Clock Tower (Inside)": RE4RegionData(["R218-Gatekeeper"]),
    "R218-Gatekeeper": RE4RegionData(["R215-False Bottom Room"]),
    "R215-False Bottom Room": RE4RegionData(["R229-Spike Pit"]),
    "R229-Spike Pit": RE4RegionData(["R221-Novistador Boss"]),
    "R221-Novistador Boss": RE4RegionData(["R220-Merchant Area"]),
    "R220-Merchant Area": RE4RegionData(["R223-Mine Shaft"]),
    "R223-Mine Shaft": RE4RegionData(["R224-El Gigante Lava Arena"]),
    "R224-El Gigante Lava Arena": RE4RegionData(["R21d-Novistador Ravine"]),
    "R21d-Novistador Ravine": RE4RegionData(["R225-Dungeon Entrance", "R226-Cathedral"]),
    "R225-Dungeon Entrance": RE4RegionData(["R21a-Dungeon One"]),
    "R21a-Dungeon One": RE4RegionData(["R21b-Minecart Ride"]),
    "R21b-Minecart Ride": RE4RegionData(["R225-Dungeon Entrance"]),
    "R226-Cathedral": RE4RegionData(["R227-Tower"]),
    "R227-Tower": RE4RegionData(["R228-Salazar Fight"]),
    "R228-Salazar Fight": RE4RegionData(["R22a-Tower Exterior"]),
    "R22a-Tower Exterior": RE4RegionData(["R300-Island"]),
    "R300-Island": RE4RegionData(["R301-Second Island Level"]),
    "R301-Second Island Level": RE4RegionData(["R303-Prison Kitchen"]), # R302 has no entry
    "R303-Prison Kitchen": RE4RegionData(["R304-Cellar"]),
    "R304-Cellar": RE4RegionData(["R305-Locker Room"]),
    "R305-Locker Room": RE4RegionData(["R306-Main Hall"]),
    "R306-Main Hall": RE4RegionData(["R307-Operating Room", "R308-Cryo Storage", "R30b-Garbage Room"]),
    "R307-Operating Room": RE4RegionData([]),
    "R308-Cryo Storage": RE4RegionData([]),
    "R30b-Garbage Room": RE4RegionData(["R30c-Electrical Room", "R310-Garbage Room Bottom"]),
    "R30c-Electrical Room": RE4RegionData(["R309-Lab"]),
    "R309-Lab": RE4RegionData(["R30a-Communication Tower"]),
    "R30a-Communication Tower": RE4RegionData([]),
    "R310-Garbage Room Bottom": RE4RegionData(["R311-Cooling System"]),
    "R311-Cooling System": RE4RegionData(["R30d-Employee Area"]),
    "R30d-Employee Area": RE4RegionData(["R312-Merchant Room", "R313-Truck"]), # R313-Truck not in list, this is a guess. R314 has no entry and I'm unsure where it would lead.
    "R312-Merchant Room": RE4RegionData([]),
    "R313-Truck": RE4RegionData(["R315-Post Truck"]),
    "R315-Post Truck": RE4RegionData(["R316-Chapel"]),
    "R316-Chapel": RE4RegionData(["R317-Krauser Knife Battle"]),
    "R317-Krauser Knife Battle": RE4RegionData(["R318-Laser Room"]),
    "R318-Laser Room": RE4RegionData(["R31a-Cave Entrance"]),
    "R31a-Cave Entrance": RE4RegionData(["R31b-U-3"]),
    "R31b-U-3": RE4RegionData(["R31d-Pass Through"]),
    "R31d-Pass Through": RE4RegionData(["R31c-Krauser Fight"]),
    "R31c-Krauser Fight": RE4RegionData(["R320-Complex"]),
    "R320-Complex": RE4RegionData(["R321-MIIIIIIIKEEEEE"]),
    "R321-MIIIIIIIKEEEEE": RE4RegionData(["R325-Ada Cutscene"]),
    "R325-Ada Cutscene": RE4RegionData(["R326-Prison"]),
    "R326-Prison": RE4RegionData(["R327-Courtyard"]),
    "R327-Courtyard": RE4RegionData(["R329-Ashley Electric Chair"]),
    "R329-Ashley Electric Chair": RE4RegionData(["R330-Leon Electric Cahir"]),
    "R330-Leon Electric Chair": RE4RegionData(["R331-Final Merchant"]),
    "R331-Final Merchant": RE4RegionData(["R332-Saddler Fight", "R333-Jetski"]),
    "R332-Saddler Fight": RE4RegionData([]),
    "R333-Jetski": RE4RegionData([]),
    "R400-Mercenaries Village": RE4RegionData([]),
    "R402-Mercenaries Castle": RE4RegionData([]),
    "R403-Mercenaries Complex": RE4RegionData([]),
    "R404-Mercenaries Water": RE4RegionData([]),
    "R500-Separate Ways-Village": RE4RegionData(["R501-Separate Ways-Underpass"]),
    "R501-Separate Ways-Underpass": RE4RegionData(["R502-Separate Ways-Church", "R504-Separate Ways-Village After Bell"]),
    "R502-Separate Ways-Church": RE4RegionData(["R503-Separate Ways-Inside Church"]),
    "R503-Separate Ways-Inside Church": RE4RegionData([]),
    "R504-Separate Ways-Village After Bell": RE4RegionData(["R505-Separate Ways-Farm"]),
    "R505-Separate Ways-Farm": RE4RegionData(["R506-Separate Ways-The Mayor's House"]),
    "R506-Separate Ways-The Mayor's House": RE4RegionData(["R507-Separate Ways-The Old House"]),
    "R507-Separate Ways-The Old House": RE4RegionData(["R508-Separate Ways-Gondola"]),
    "R508-Separate Ways-Gondola": RE4RegionData(["R50b-Separate Ways-Barn", "R50a-Separate Ways-Split Road"]),
    "R50b-Separate Ways-Barn": RE4RegionData([]),
    "R50a-Separate Ways-Split Road": RE4RegionData(["R509-Separate Ways-Cabin"]),
    "R509-Separate Ways-Cabin": RE4RegionData(["R50e-Separate Ways-Hedge Maze"]),
    "R50e-Separate Ways-Hedge Maze": RE4RegionData(["R50d-Separate Ways-Hallway", "R50f-Separate Ways-Gallery"]),
    "R50d-Separate Ways-Hallway": RE4RegionData(["R50f-Separate Ways-Gallery"]),
    "R50f-Separate Ways-Gallery": RE4RegionData(["R510-Separate Ways-Gallery 2"]),
    "R510-Separate Ways-Gallery 2": RE4RegionData(["R50c-Separate Ways-Castle Main Hall"]),
    "R50c-Separate Ways-Castle Main Hall": RE4RegionData(["R512-Separate Ways-Truck Route"]),
    "R512-Separate Ways-Truck Route": RE4RegionData(["R513-Separate Ways-Boat"]),
    "R513-Separate Ways-Boat": RE4RegionData(["R514-Separate Ways-???"]), # This is how it's listed in RE4 Tweaks
    "R514-Separate Ways-???": RE4RegionData(["R515-Separate Ways-Truck Crash"]),
    "R515-Separate Ways-Truck Crash": RE4RegionData(["R516-Separate Ways-Island Chapel"]),
    "R516-Separate Ways-Island Chapel": RE4RegionData(["R517-Separate Ways-Krauser Knife"]),
    "R517-Separate Ways-Krauser Knife": RE4RegionData(["R518-Separate Ways-Complex"]),
    "R518-Separate Ways-Complex": RE4RegionData(["R519-Separate Ways-MIIIIIIKE"]),
    "R519-Separate Ways-MIIIIIIKE": RE4RegionData(["R51a-Separate Ways-Cutscene"]),
    "R51a-Separate Ways-Cutscene": RE4RegionData(["R51b-Separate Ways-Prison"]),
    "R51b-Separate Ways-Prison": RE4RegionData(["R51c-Separate Ways-Courtyard"]),
    "R51c-Separate Ways-Courtyard": RE4RegionData(["R51d-Separate Ways-Ashley Electric Chair"]),
    "R51d-Separate Ways-Ashley Electric Chair": RE4RegionData(["R51e-Separate Ways-Saddler Fight"])
}

def get_exit(region, exit_name):
    for exit in region.exits:
        if exit.connected_region.name == exit_name:
            return exit